name: Syncing to the server
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: sigsoft
    steps:
      - name: ğŸ”‘ Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.HOST }}" > ~/.ssh/known_hosts

      - name: ğŸš€ Deploy using rsync
        run: rsync --archive --delete --stats -e 'ssh -p 7822' '/' ${{ secrets.REMOTE_DEST }}
      - run: echo "ğŸ–¥ï¸ We have just synchronized."
